services:
  adapters:
    container_name: maim-bot-adapters
    image: tripitz/maibot-adapter:0.8.0
    environment:
      - TZ=Asia/Shanghai
#    ports:
#      - "8095:8095"
    volumes:
      - ./docker-config/adapters/config.toml:/adapters/config.toml
    restart: always
    networks:
      - maim_bot
  core:
    container_name: maim-bot-core
    image: tripitz/maibot-core:0.8.0
    environment:
      - TZ=Asia/Shanghai
      - EULA_AGREE=bda99dca873f5d8044e9987eac417e01 # 同意EULA
      - PRIVACY_AGREE=42dddb3cbe2b784b45a2781407b298a1 # 同意EULA
#    ports:
#      - "8000:8000"
    volumes:
      - ./docker-config/mmc/.env:/MaiMBot/.env # 持久化env配置文件
      - ./docker-config/mmc:/MaiMBot/config # 持久化bot配置文件
      - ./docker-config/entrypoint.sh:/opt/entrypoint.sh # 持久化启动脚本（负责安装插件依赖和启动mmc）
      - ./data/MaiMBot/maibot_statistics.html:/MaiMBot/maibot_statistics.html #统计数据输出
      - ./data/MaiMBot:/MaiMBot/data # NapCat 和 NoneBot 共享此卷，否则发送图片会有问题
      - ./modules/plugins:/MaiMBot/plugins # 持久化插件目录
      - ./modules/built_in:/MaiMBot/src/plugins/built_in # 持久化内置加载器(内置插件)
    restart: always
    networks:
      - maim_bot
  napcat:
    environment:
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
      - TZ=Asia/Shanghai
    ports:
      - "6099:6099"
    volumes:
      - ./docker-config/napcat:/app/napcat/config # 持久化napcat配置文件
      - ./data/qq:/app/.config/QQ # 持久化QQ本体并同步qq表情和图片到adapters
      - ./data/MaiMBot:/MaiMBot/data # NapCat 和 NoneBot 共享此卷，否则发送图片会有问题
    container_name: maim-bot-napcat
    restart: always
    image: mlikiowa/napcat-docker:latest
    networks:
      - maim_bot
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    restart: always
    ports:
      - "8120:8080"
    volumes:
      - ./data/MaiMBot:/data/MaiMBot
    environment:
      - SQLITE_DATABASE=MaiMBot/MaiBot.db  # 你的数据库文件
    networks:
      - maim_bot
networks:
  maim_bot:
    driver: bridge
